### ISSUE TITLE
Use *zap.SugaredLogger instead of *zap.Logger

### ISSUE THREAD

**Issue by akshayjshah** [viru/grpczap#3]
Hi friends! I'm one of the authors of zap, and I'd love to help out a little. Are you open to some performance improvements?

In particular, you'll benefit from wrapping the `*zap.SugaredLogger` type instead of doing your own string formatting - because it's internal to `zap`, it's able to avoid formatting overhead where possible.

Are you open to a PR?

**Comment by pawelkowalak** [comment]
Hi, thanks for your interest and of course we're open for PRs :)

**Comment by akshayjshah** [comment]
Since we're using gRPC a bit internally, we've included a gRPC-compatible wrapper in zap itself.
